//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVCReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacheAssignation
    {
        public int TacheAssignationID { get; set; }
        public string Collaborateur { get; set; }
        public Nullable<int> Tache { get; set; }
    }
}
