//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVCReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tach
    {
        public int TacheID { get; set; }
        public string Titre { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public Nullable<System.DateTime> DateFinReelle { get; set; }
        public string Auteur { get; set; }
        public Nullable<int> Priorite { get; set; }
        public string Statut { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
